// <auto-generated />
using System;
using MRV.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRV.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MRV.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(662),
                            Description = "Caverna do Dragão",
                            Email = "mestre@magos.com",
                            FirstName = "Mestre",
                            FullName = "Mestre do Magos",
                            PhoneNumber = "99 999999999",
                            Price = 100m,
                            Suburb = "A Noite sem Amanhã"
                        },
                        new
                        {
                            Id = 2,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1314),
                            Description = "Caverna do Dragão",
                            Email = "hank@ded.com",
                            FirstName = "Hank",
                            FullName = "Hank Arqueiro",
                            PhoneNumber = "11 111111111",
                            Price = 675.00m,
                            Suburb = "O Olho do Observador"
                        },
                        new
                        {
                            Id = 3,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1764),
                            Description = "Caverna do Dragão",
                            Email = "eric@ded.com",
                            FirstName = "Eric",
                            FullName = "Eric Cavaleiro",
                            PhoneNumber = "22 222222222",
                            Price = 720.00m,
                            Suburb = "O Salão dos Ossos"
                        },
                        new
                        {
                            Id = 4,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1771),
                            Description = "Caverna do Dragão",
                            Email = "diana@ded.com",
                            FirstName = "Diana",
                            FullName = "Diana Acrobata",
                            PhoneNumber = "33 333333333",
                            Price = 320m,
                            Suburb = "O Vale dos Unicórnios"
                        },
                        new
                        {
                            Id = 5,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1772),
                            Description = "Caverna do Dragão",
                            Email = "sheila@ded.com",
                            FirstName = "Sheila",
                            FullName = "Sheila Ladina",
                            PhoneNumber = "44 444444444",
                            Price = 500m,
                            Suburb = "Em Busca do Mestre dos Magos"
                        },
                        new
                        {
                            Id = 6,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1774),
                            Description = "Caverna do Dragão",
                            Email = "bobby@ded.com",
                            FirstName = "Bobby",
                            FullName = "Bobby Barbaro",
                            PhoneNumber = "55 555555555",
                            Price = 450m,
                            Suburb = "A Bela e a Fera do Pântano"
                        },
                        new
                        {
                            Id = 7,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1775),
                            Description = "Caverna do Dragão",
                            Email = "uni@ded.com",
                            FirstName = "Uni",
                            FullName = "Uni Unicornio",
                            PhoneNumber = "66 666666666",
                            Price = 450.90m,
                            Suburb = "Prisão sem Muros"
                        },
                        new
                        {
                            Id = 8,
                            Accepted = false,
                            Category = "Fantasia",
                            DateCreated = new DateTime(2025, 6, 8, 18, 49, 54, 98, DateTimeKind.Utc).AddTicks(1777),
                            Description = "Caverna do Dragão",
                            Email = "presto@ded.com",
                            FirstName = "Presto",
                            FullName = "Presto Mago",
                            PhoneNumber = "77 777777777",
                            Price = 562.50m,
                            Suburb = "Servo do Mal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
